all: increment consecutive safe_increment

increment:
	cc increment.c -o increment;

consecutive:
	cc consecutive.c -o consecutive;

safe_increment:
	cc safe_increment.c -o safe_increment;

clean:
	rm -f increment;
	rm -f consecutive;
	rm -f safe_increment;
